// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Node.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nbrpc {
  public static partial class NodeRpc
  {
    static readonly string __ServiceName = "nbrpc.NodeRpc";

    static readonly grpc::Marshaller<global::Nbrpc.AddNodeRequest> __Marshaller_nbrpc_AddNodeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.AddNodeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.CommonReply> __Marshaller_nbrpc_CommonReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.CommonReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.RemoveNodeRequest> __Marshaller_nbrpc_RemoveNodeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.RemoveNodeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.RenameNodeRequest> __Marshaller_nbrpc_RenameNodeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.RenameNodeRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Nbrpc.AddNodeRequest, global::Nbrpc.CommonReply> __Method_AddNode = new grpc::Method<global::Nbrpc.AddNodeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddNode",
        __Marshaller_nbrpc_AddNodeRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.RemoveNodeRequest, global::Nbrpc.CommonReply> __Method_RemoveNode = new grpc::Method<global::Nbrpc.RemoveNodeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveNode",
        __Marshaller_nbrpc_RemoveNodeRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.RenameNodeRequest, global::Nbrpc.CommonReply> __Method_RenameNode = new grpc::Method<global::Nbrpc.RenameNodeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RenameNode",
        __Marshaller_nbrpc_RenameNodeRequest,
        __Marshaller_nbrpc_CommonReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nbrpc.NodeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NodeRpc</summary>
    [grpc::BindServiceMethod(typeof(NodeRpc), "BindService")]
    public abstract partial class NodeRpcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> AddNode(global::Nbrpc.AddNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> RemoveNode(global::Nbrpc.RemoveNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> RenameNode(global::Nbrpc.RenameNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NodeRpc</summary>
    public partial class NodeRpcClient : grpc::ClientBase<NodeRpcClient>
    {
      /// <summary>Creates a new client for NodeRpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NodeRpcClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NodeRpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NodeRpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NodeRpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NodeRpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Nbrpc.CommonReply AddNode(global::Nbrpc.AddNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply AddNode(global::Nbrpc.AddNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> AddNodeAsync(global::Nbrpc.AddNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> AddNodeAsync(global::Nbrpc.AddNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddNode, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply RemoveNode(global::Nbrpc.RemoveNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply RemoveNode(global::Nbrpc.RemoveNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RemoveNodeAsync(global::Nbrpc.RemoveNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RemoveNodeAsync(global::Nbrpc.RemoveNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveNode, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply RenameNode(global::Nbrpc.RenameNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenameNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply RenameNode(global::Nbrpc.RenameNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RenameNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RenameNodeAsync(global::Nbrpc.RenameNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenameNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RenameNodeAsync(global::Nbrpc.RenameNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RenameNode, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NodeRpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NodeRpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NodeRpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddNode, serviceImpl.AddNode)
          .AddMethod(__Method_RemoveNode, serviceImpl.RemoveNode)
          .AddMethod(__Method_RenameNode, serviceImpl.RenameNode).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NodeRpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.AddNodeRequest, global::Nbrpc.CommonReply>(serviceImpl.AddNode));
      serviceBinder.AddMethod(__Method_RemoveNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.RemoveNodeRequest, global::Nbrpc.CommonReply>(serviceImpl.RemoveNode));
      serviceBinder.AddMethod(__Method_RenameNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.RenameNodeRequest, global::Nbrpc.CommonReply>(serviceImpl.RenameNode));
    }

  }
}
#endregion
