// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Node.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Nbrpc {
  public static partial class NodeRpc
  {
    static readonly string __ServiceName = "nbrpc.NodeRpc";

    static readonly grpc::Marshaller<global::Nbrpc.AddNodeRequest> __Marshaller_nbrpc_AddNodeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.AddNodeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.CommonReply> __Marshaller_nbrpc_CommonReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.CommonReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.RemoveNodeRequest> __Marshaller_nbrpc_RemoveNodeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.RemoveNodeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.RenameNodeRequest> __Marshaller_nbrpc_RenameNodeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.RenameNodeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyBoolRequest> __Marshaller_nbrpc_SetPropertyBoolRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyBoolRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyInt8Request> __Marshaller_nbrpc_SetPropertyInt8Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyInt8Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyInt16Request> __Marshaller_nbrpc_SetPropertyInt16Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyInt16Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyInt32Request> __Marshaller_nbrpc_SetPropertyInt32Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyInt32Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyInt64Request> __Marshaller_nbrpc_SetPropertyInt64Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyInt64Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyUInt8Request> __Marshaller_nbrpc_SetPropertyUInt8Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyUInt8Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyUInt16Request> __Marshaller_nbrpc_SetPropertyUInt16Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyUInt16Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyUInt32Request> __Marshaller_nbrpc_SetPropertyUInt32Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyUInt32Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyUInt64Request> __Marshaller_nbrpc_SetPropertyUInt64Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyUInt64Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyFloatRequest> __Marshaller_nbrpc_SetPropertyFloatRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyFloatRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyDoubleRequest> __Marshaller_nbrpc_SetPropertyDoubleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyDoubleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyStringRequest> __Marshaller_nbrpc_SetPropertyStringRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyStringRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyVec2Request> __Marshaller_nbrpc_SetPropertyVec2Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyVec2Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyVec3Request> __Marshaller_nbrpc_SetPropertyVec3Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyVec3Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyVec4Request> __Marshaller_nbrpc_SetPropertyVec4Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyVec4Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyColorRequest> __Marshaller_nbrpc_SetPropertyColorRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyColorRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyDateTimeRequest> __Marshaller_nbrpc_SetPropertyDateTimeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyDateTimeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyTimeSpanRequest> __Marshaller_nbrpc_SetPropertyTimeSpanRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyTimeSpanRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyThicknessRequest> __Marshaller_nbrpc_SetPropertyThicknessRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyThicknessRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyEnumRequest> __Marshaller_nbrpc_SetPropertyEnumRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyEnumRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertySolidColorBrushRequest> __Marshaller_nbrpc_SetPropertySolidColorBrushRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertySolidColorBrushRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyImageBrushRequest> __Marshaller_nbrpc_SetPropertyImageBrushRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyImageBrushRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Nbrpc.SetPropertyLinearGradientBrushRequest> __Marshaller_nbrpc_SetPropertyLinearGradientBrushRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Nbrpc.SetPropertyLinearGradientBrushRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Nbrpc.AddNodeRequest, global::Nbrpc.CommonReply> __Method_AddNode = new grpc::Method<global::Nbrpc.AddNodeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddNode",
        __Marshaller_nbrpc_AddNodeRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.RemoveNodeRequest, global::Nbrpc.CommonReply> __Method_RemoveNode = new grpc::Method<global::Nbrpc.RemoveNodeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveNode",
        __Marshaller_nbrpc_RemoveNodeRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.RenameNodeRequest, global::Nbrpc.CommonReply> __Method_RenameNode = new grpc::Method<global::Nbrpc.RenameNodeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RenameNode",
        __Marshaller_nbrpc_RenameNodeRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyBoolRequest, global::Nbrpc.CommonReply> __Method_SetPropertyBool = new grpc::Method<global::Nbrpc.SetPropertyBoolRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyBool",
        __Marshaller_nbrpc_SetPropertyBoolRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyInt8Request, global::Nbrpc.CommonReply> __Method_SetPropertyInt8 = new grpc::Method<global::Nbrpc.SetPropertyInt8Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyInt8",
        __Marshaller_nbrpc_SetPropertyInt8Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyInt16Request, global::Nbrpc.CommonReply> __Method_SetPropertyInt16 = new grpc::Method<global::Nbrpc.SetPropertyInt16Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyInt16",
        __Marshaller_nbrpc_SetPropertyInt16Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyInt32Request, global::Nbrpc.CommonReply> __Method_SetPropertyInt32 = new grpc::Method<global::Nbrpc.SetPropertyInt32Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyInt32",
        __Marshaller_nbrpc_SetPropertyInt32Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyInt64Request, global::Nbrpc.CommonReply> __Method_SetPropertyInt64 = new grpc::Method<global::Nbrpc.SetPropertyInt64Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyInt64",
        __Marshaller_nbrpc_SetPropertyInt64Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyUInt8Request, global::Nbrpc.CommonReply> __Method_SetPropertyUInt8 = new grpc::Method<global::Nbrpc.SetPropertyUInt8Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyUInt8",
        __Marshaller_nbrpc_SetPropertyUInt8Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyUInt16Request, global::Nbrpc.CommonReply> __Method_SetPropertyUInt16 = new grpc::Method<global::Nbrpc.SetPropertyUInt16Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyUInt16",
        __Marshaller_nbrpc_SetPropertyUInt16Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyUInt32Request, global::Nbrpc.CommonReply> __Method_SetPropertyUInt32 = new grpc::Method<global::Nbrpc.SetPropertyUInt32Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyUInt32",
        __Marshaller_nbrpc_SetPropertyUInt32Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyUInt64Request, global::Nbrpc.CommonReply> __Method_SetPropertyUInt64 = new grpc::Method<global::Nbrpc.SetPropertyUInt64Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyUInt64",
        __Marshaller_nbrpc_SetPropertyUInt64Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyFloatRequest, global::Nbrpc.CommonReply> __Method_SetPropertyFloat = new grpc::Method<global::Nbrpc.SetPropertyFloatRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyFloat",
        __Marshaller_nbrpc_SetPropertyFloatRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyDoubleRequest, global::Nbrpc.CommonReply> __Method_SetPropertyDouble = new grpc::Method<global::Nbrpc.SetPropertyDoubleRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyDouble",
        __Marshaller_nbrpc_SetPropertyDoubleRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyStringRequest, global::Nbrpc.CommonReply> __Method_SetPropertyString = new grpc::Method<global::Nbrpc.SetPropertyStringRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyString",
        __Marshaller_nbrpc_SetPropertyStringRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyVec2Request, global::Nbrpc.CommonReply> __Method_SetPropertyVec2 = new grpc::Method<global::Nbrpc.SetPropertyVec2Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyVec2",
        __Marshaller_nbrpc_SetPropertyVec2Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyVec3Request, global::Nbrpc.CommonReply> __Method_SetPropertyVec3 = new grpc::Method<global::Nbrpc.SetPropertyVec3Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyVec3",
        __Marshaller_nbrpc_SetPropertyVec3Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyVec4Request, global::Nbrpc.CommonReply> __Method_SetPropertyVec4 = new grpc::Method<global::Nbrpc.SetPropertyVec4Request, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyVec4",
        __Marshaller_nbrpc_SetPropertyVec4Request,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyColorRequest, global::Nbrpc.CommonReply> __Method_SetPropertyColor = new grpc::Method<global::Nbrpc.SetPropertyColorRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyColor",
        __Marshaller_nbrpc_SetPropertyColorRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyDateTimeRequest, global::Nbrpc.CommonReply> __Method_SetPropertyDateTime = new grpc::Method<global::Nbrpc.SetPropertyDateTimeRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyDateTime",
        __Marshaller_nbrpc_SetPropertyDateTimeRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyTimeSpanRequest, global::Nbrpc.CommonReply> __Method_SetPropertyTimeSpan = new grpc::Method<global::Nbrpc.SetPropertyTimeSpanRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyTimeSpan",
        __Marshaller_nbrpc_SetPropertyTimeSpanRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyThicknessRequest, global::Nbrpc.CommonReply> __Method_SetPropertyThickness = new grpc::Method<global::Nbrpc.SetPropertyThicknessRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyThickness",
        __Marshaller_nbrpc_SetPropertyThicknessRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyEnumRequest, global::Nbrpc.CommonReply> __Method_SetPropertyEnum = new grpc::Method<global::Nbrpc.SetPropertyEnumRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyEnum",
        __Marshaller_nbrpc_SetPropertyEnumRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertySolidColorBrushRequest, global::Nbrpc.CommonReply> __Method_SetPropertySolidColorBrush = new grpc::Method<global::Nbrpc.SetPropertySolidColorBrushRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertySolidColorBrush",
        __Marshaller_nbrpc_SetPropertySolidColorBrushRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyImageBrushRequest, global::Nbrpc.CommonReply> __Method_SetPropertyImageBrush = new grpc::Method<global::Nbrpc.SetPropertyImageBrushRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyImageBrush",
        __Marshaller_nbrpc_SetPropertyImageBrushRequest,
        __Marshaller_nbrpc_CommonReply);

    static readonly grpc::Method<global::Nbrpc.SetPropertyLinearGradientBrushRequest, global::Nbrpc.CommonReply> __Method_SetPropertyLinearGradientBrush = new grpc::Method<global::Nbrpc.SetPropertyLinearGradientBrushRequest, global::Nbrpc.CommonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetPropertyLinearGradientBrush",
        __Marshaller_nbrpc_SetPropertyLinearGradientBrushRequest,
        __Marshaller_nbrpc_CommonReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Nbrpc.NodeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NodeRpc</summary>
    [grpc::BindServiceMethod(typeof(NodeRpc), "BindService")]
    public abstract partial class NodeRpcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> AddNode(global::Nbrpc.AddNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> RemoveNode(global::Nbrpc.RemoveNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> RenameNode(global::Nbrpc.RenameNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyBool(global::Nbrpc.SetPropertyBoolRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyInt8(global::Nbrpc.SetPropertyInt8Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyInt16(global::Nbrpc.SetPropertyInt16Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyInt32(global::Nbrpc.SetPropertyInt32Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyInt64(global::Nbrpc.SetPropertyInt64Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyUInt8(global::Nbrpc.SetPropertyUInt8Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyUInt16(global::Nbrpc.SetPropertyUInt16Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyUInt32(global::Nbrpc.SetPropertyUInt32Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyUInt64(global::Nbrpc.SetPropertyUInt64Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyFloat(global::Nbrpc.SetPropertyFloatRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyDouble(global::Nbrpc.SetPropertyDoubleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyString(global::Nbrpc.SetPropertyStringRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyVec2(global::Nbrpc.SetPropertyVec2Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyVec3(global::Nbrpc.SetPropertyVec3Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyVec4(global::Nbrpc.SetPropertyVec4Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyColor(global::Nbrpc.SetPropertyColorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyDateTime(global::Nbrpc.SetPropertyDateTimeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyTimeSpan(global::Nbrpc.SetPropertyTimeSpanRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyThickness(global::Nbrpc.SetPropertyThicknessRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyEnum(global::Nbrpc.SetPropertyEnumRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertySolidColorBrush(global::Nbrpc.SetPropertySolidColorBrushRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyImageBrush(global::Nbrpc.SetPropertyImageBrushRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Nbrpc.CommonReply> SetPropertyLinearGradientBrush(global::Nbrpc.SetPropertyLinearGradientBrushRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NodeRpc</summary>
    public partial class NodeRpcClient : grpc::ClientBase<NodeRpcClient>
    {
      /// <summary>Creates a new client for NodeRpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NodeRpcClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NodeRpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NodeRpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NodeRpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NodeRpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Nbrpc.CommonReply AddNode(global::Nbrpc.AddNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply AddNode(global::Nbrpc.AddNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> AddNodeAsync(global::Nbrpc.AddNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> AddNodeAsync(global::Nbrpc.AddNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddNode, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply RemoveNode(global::Nbrpc.RemoveNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply RemoveNode(global::Nbrpc.RemoveNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RemoveNodeAsync(global::Nbrpc.RemoveNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RemoveNodeAsync(global::Nbrpc.RemoveNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveNode, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply RenameNode(global::Nbrpc.RenameNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenameNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply RenameNode(global::Nbrpc.RenameNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RenameNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RenameNodeAsync(global::Nbrpc.RenameNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenameNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> RenameNodeAsync(global::Nbrpc.RenameNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RenameNode, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyBool(global::Nbrpc.SetPropertyBoolRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyBool(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyBool(global::Nbrpc.SetPropertyBoolRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyBool, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyBoolAsync(global::Nbrpc.SetPropertyBoolRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyBoolAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyBoolAsync(global::Nbrpc.SetPropertyBoolRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyBool, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt8(global::Nbrpc.SetPropertyInt8Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt8(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt8(global::Nbrpc.SetPropertyInt8Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyInt8, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt8Async(global::Nbrpc.SetPropertyInt8Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt8Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt8Async(global::Nbrpc.SetPropertyInt8Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyInt8, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt16(global::Nbrpc.SetPropertyInt16Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt16(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt16(global::Nbrpc.SetPropertyInt16Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyInt16, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt16Async(global::Nbrpc.SetPropertyInt16Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt16Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt16Async(global::Nbrpc.SetPropertyInt16Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyInt16, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt32(global::Nbrpc.SetPropertyInt32Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt32(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt32(global::Nbrpc.SetPropertyInt32Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyInt32, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt32Async(global::Nbrpc.SetPropertyInt32Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt32Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt32Async(global::Nbrpc.SetPropertyInt32Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyInt32, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt64(global::Nbrpc.SetPropertyInt64Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt64(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyInt64(global::Nbrpc.SetPropertyInt64Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyInt64, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt64Async(global::Nbrpc.SetPropertyInt64Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyInt64Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyInt64Async(global::Nbrpc.SetPropertyInt64Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyInt64, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt8(global::Nbrpc.SetPropertyUInt8Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt8(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt8(global::Nbrpc.SetPropertyUInt8Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyUInt8, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt8Async(global::Nbrpc.SetPropertyUInt8Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt8Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt8Async(global::Nbrpc.SetPropertyUInt8Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyUInt8, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt16(global::Nbrpc.SetPropertyUInt16Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt16(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt16(global::Nbrpc.SetPropertyUInt16Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyUInt16, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt16Async(global::Nbrpc.SetPropertyUInt16Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt16Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt16Async(global::Nbrpc.SetPropertyUInt16Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyUInt16, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt32(global::Nbrpc.SetPropertyUInt32Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt32(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt32(global::Nbrpc.SetPropertyUInt32Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyUInt32, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt32Async(global::Nbrpc.SetPropertyUInt32Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt32Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt32Async(global::Nbrpc.SetPropertyUInt32Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyUInt32, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt64(global::Nbrpc.SetPropertyUInt64Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt64(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyUInt64(global::Nbrpc.SetPropertyUInt64Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyUInt64, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt64Async(global::Nbrpc.SetPropertyUInt64Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyUInt64Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyUInt64Async(global::Nbrpc.SetPropertyUInt64Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyUInt64, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyFloat(global::Nbrpc.SetPropertyFloatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyFloat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyFloat(global::Nbrpc.SetPropertyFloatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyFloat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyFloatAsync(global::Nbrpc.SetPropertyFloatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyFloatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyFloatAsync(global::Nbrpc.SetPropertyFloatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyFloat, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyDouble(global::Nbrpc.SetPropertyDoubleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyDouble(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyDouble(global::Nbrpc.SetPropertyDoubleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyDouble, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyDoubleAsync(global::Nbrpc.SetPropertyDoubleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyDoubleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyDoubleAsync(global::Nbrpc.SetPropertyDoubleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyDouble, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyString(global::Nbrpc.SetPropertyStringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyString(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyString(global::Nbrpc.SetPropertyStringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyString, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyStringAsync(global::Nbrpc.SetPropertyStringRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyStringAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyStringAsync(global::Nbrpc.SetPropertyStringRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyString, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyVec2(global::Nbrpc.SetPropertyVec2Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyVec2(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyVec2(global::Nbrpc.SetPropertyVec2Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyVec2, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyVec2Async(global::Nbrpc.SetPropertyVec2Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyVec2Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyVec2Async(global::Nbrpc.SetPropertyVec2Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyVec2, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyVec3(global::Nbrpc.SetPropertyVec3Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyVec3(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyVec3(global::Nbrpc.SetPropertyVec3Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyVec3, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyVec3Async(global::Nbrpc.SetPropertyVec3Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyVec3Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyVec3Async(global::Nbrpc.SetPropertyVec3Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyVec3, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyVec4(global::Nbrpc.SetPropertyVec4Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyVec4(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyVec4(global::Nbrpc.SetPropertyVec4Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyVec4, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyVec4Async(global::Nbrpc.SetPropertyVec4Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyVec4Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyVec4Async(global::Nbrpc.SetPropertyVec4Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyVec4, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyColor(global::Nbrpc.SetPropertyColorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyColor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyColor(global::Nbrpc.SetPropertyColorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyColor, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyColorAsync(global::Nbrpc.SetPropertyColorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyColorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyColorAsync(global::Nbrpc.SetPropertyColorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyColor, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyDateTime(global::Nbrpc.SetPropertyDateTimeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyDateTime(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyDateTime(global::Nbrpc.SetPropertyDateTimeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyDateTime, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyDateTimeAsync(global::Nbrpc.SetPropertyDateTimeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyDateTimeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyDateTimeAsync(global::Nbrpc.SetPropertyDateTimeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyDateTime, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyTimeSpan(global::Nbrpc.SetPropertyTimeSpanRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyTimeSpan(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyTimeSpan(global::Nbrpc.SetPropertyTimeSpanRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyTimeSpan, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyTimeSpanAsync(global::Nbrpc.SetPropertyTimeSpanRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyTimeSpanAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyTimeSpanAsync(global::Nbrpc.SetPropertyTimeSpanRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyTimeSpan, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyThickness(global::Nbrpc.SetPropertyThicknessRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyThickness(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyThickness(global::Nbrpc.SetPropertyThicknessRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyThickness, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyThicknessAsync(global::Nbrpc.SetPropertyThicknessRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyThicknessAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyThicknessAsync(global::Nbrpc.SetPropertyThicknessRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyThickness, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyEnum(global::Nbrpc.SetPropertyEnumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyEnum(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyEnum(global::Nbrpc.SetPropertyEnumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyEnum, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyEnumAsync(global::Nbrpc.SetPropertyEnumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyEnumAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyEnumAsync(global::Nbrpc.SetPropertyEnumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyEnum, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertySolidColorBrush(global::Nbrpc.SetPropertySolidColorBrushRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertySolidColorBrush(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertySolidColorBrush(global::Nbrpc.SetPropertySolidColorBrushRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertySolidColorBrush, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertySolidColorBrushAsync(global::Nbrpc.SetPropertySolidColorBrushRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertySolidColorBrushAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertySolidColorBrushAsync(global::Nbrpc.SetPropertySolidColorBrushRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertySolidColorBrush, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyImageBrush(global::Nbrpc.SetPropertyImageBrushRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyImageBrush(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyImageBrush(global::Nbrpc.SetPropertyImageBrushRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyImageBrush, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyImageBrushAsync(global::Nbrpc.SetPropertyImageBrushRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyImageBrushAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyImageBrushAsync(global::Nbrpc.SetPropertyImageBrushRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyImageBrush, null, options, request);
      }
      public virtual global::Nbrpc.CommonReply SetPropertyLinearGradientBrush(global::Nbrpc.SetPropertyLinearGradientBrushRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyLinearGradientBrush(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Nbrpc.CommonReply SetPropertyLinearGradientBrush(global::Nbrpc.SetPropertyLinearGradientBrushRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetPropertyLinearGradientBrush, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyLinearGradientBrushAsync(global::Nbrpc.SetPropertyLinearGradientBrushRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetPropertyLinearGradientBrushAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Nbrpc.CommonReply> SetPropertyLinearGradientBrushAsync(global::Nbrpc.SetPropertyLinearGradientBrushRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetPropertyLinearGradientBrush, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NodeRpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NodeRpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NodeRpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddNode, serviceImpl.AddNode)
          .AddMethod(__Method_RemoveNode, serviceImpl.RemoveNode)
          .AddMethod(__Method_RenameNode, serviceImpl.RenameNode)
          .AddMethod(__Method_SetPropertyBool, serviceImpl.SetPropertyBool)
          .AddMethod(__Method_SetPropertyInt8, serviceImpl.SetPropertyInt8)
          .AddMethod(__Method_SetPropertyInt16, serviceImpl.SetPropertyInt16)
          .AddMethod(__Method_SetPropertyInt32, serviceImpl.SetPropertyInt32)
          .AddMethod(__Method_SetPropertyInt64, serviceImpl.SetPropertyInt64)
          .AddMethod(__Method_SetPropertyUInt8, serviceImpl.SetPropertyUInt8)
          .AddMethod(__Method_SetPropertyUInt16, serviceImpl.SetPropertyUInt16)
          .AddMethod(__Method_SetPropertyUInt32, serviceImpl.SetPropertyUInt32)
          .AddMethod(__Method_SetPropertyUInt64, serviceImpl.SetPropertyUInt64)
          .AddMethod(__Method_SetPropertyFloat, serviceImpl.SetPropertyFloat)
          .AddMethod(__Method_SetPropertyDouble, serviceImpl.SetPropertyDouble)
          .AddMethod(__Method_SetPropertyString, serviceImpl.SetPropertyString)
          .AddMethod(__Method_SetPropertyVec2, serviceImpl.SetPropertyVec2)
          .AddMethod(__Method_SetPropertyVec3, serviceImpl.SetPropertyVec3)
          .AddMethod(__Method_SetPropertyVec4, serviceImpl.SetPropertyVec4)
          .AddMethod(__Method_SetPropertyColor, serviceImpl.SetPropertyColor)
          .AddMethod(__Method_SetPropertyDateTime, serviceImpl.SetPropertyDateTime)
          .AddMethod(__Method_SetPropertyTimeSpan, serviceImpl.SetPropertyTimeSpan)
          .AddMethod(__Method_SetPropertyThickness, serviceImpl.SetPropertyThickness)
          .AddMethod(__Method_SetPropertyEnum, serviceImpl.SetPropertyEnum)
          .AddMethod(__Method_SetPropertySolidColorBrush, serviceImpl.SetPropertySolidColorBrush)
          .AddMethod(__Method_SetPropertyImageBrush, serviceImpl.SetPropertyImageBrush)
          .AddMethod(__Method_SetPropertyLinearGradientBrush, serviceImpl.SetPropertyLinearGradientBrush).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NodeRpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.AddNodeRequest, global::Nbrpc.CommonReply>(serviceImpl.AddNode));
      serviceBinder.AddMethod(__Method_RemoveNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.RemoveNodeRequest, global::Nbrpc.CommonReply>(serviceImpl.RemoveNode));
      serviceBinder.AddMethod(__Method_RenameNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.RenameNodeRequest, global::Nbrpc.CommonReply>(serviceImpl.RenameNode));
      serviceBinder.AddMethod(__Method_SetPropertyBool, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyBoolRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyBool));
      serviceBinder.AddMethod(__Method_SetPropertyInt8, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyInt8Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyInt8));
      serviceBinder.AddMethod(__Method_SetPropertyInt16, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyInt16Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyInt16));
      serviceBinder.AddMethod(__Method_SetPropertyInt32, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyInt32Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyInt32));
      serviceBinder.AddMethod(__Method_SetPropertyInt64, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyInt64Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyInt64));
      serviceBinder.AddMethod(__Method_SetPropertyUInt8, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyUInt8Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyUInt8));
      serviceBinder.AddMethod(__Method_SetPropertyUInt16, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyUInt16Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyUInt16));
      serviceBinder.AddMethod(__Method_SetPropertyUInt32, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyUInt32Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyUInt32));
      serviceBinder.AddMethod(__Method_SetPropertyUInt64, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyUInt64Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyUInt64));
      serviceBinder.AddMethod(__Method_SetPropertyFloat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyFloatRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyFloat));
      serviceBinder.AddMethod(__Method_SetPropertyDouble, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyDoubleRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyDouble));
      serviceBinder.AddMethod(__Method_SetPropertyString, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyStringRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyString));
      serviceBinder.AddMethod(__Method_SetPropertyVec2, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyVec2Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyVec2));
      serviceBinder.AddMethod(__Method_SetPropertyVec3, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyVec3Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyVec3));
      serviceBinder.AddMethod(__Method_SetPropertyVec4, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyVec4Request, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyVec4));
      serviceBinder.AddMethod(__Method_SetPropertyColor, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyColorRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyColor));
      serviceBinder.AddMethod(__Method_SetPropertyDateTime, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyDateTimeRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyDateTime));
      serviceBinder.AddMethod(__Method_SetPropertyTimeSpan, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyTimeSpanRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyTimeSpan));
      serviceBinder.AddMethod(__Method_SetPropertyThickness, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyThicknessRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyThickness));
      serviceBinder.AddMethod(__Method_SetPropertyEnum, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyEnumRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyEnum));
      serviceBinder.AddMethod(__Method_SetPropertySolidColorBrush, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertySolidColorBrushRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertySolidColorBrush));
      serviceBinder.AddMethod(__Method_SetPropertyImageBrush, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyImageBrushRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyImageBrush));
      serviceBinder.AddMethod(__Method_SetPropertyLinearGradientBrush, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Nbrpc.SetPropertyLinearGradientBrushRequest, global::Nbrpc.CommonReply>(serviceImpl.SetPropertyLinearGradientBrush));
    }

  }
}
#endregion
